### ISSUE TITLE
Add OER project

### ISSUE THREAD

**Issue by emiliom** [uw-echospace/uw-echospace.github.io#1]
Add OER project to the [list of projects](https://uw-echospace.github.io/#projects). Include link to the OER FY21 award announcement page, https://oceanexplorer.noaa.gov/news/oer-updates/2021/fy21-ffo-schedule.html

Folder where this is done: https://github.com/uw-echospace/uw-echospace.github.io/tree/master/project. (But it looks like the content we actually edit is at https://github.com/uw-echospace/group-website/tree/master/content/project?)

I'll do this. This issue is a reminder to myself :wink:

**Comment by leewujung** [comment]
Great, thanks!
