### ISSUE TITLE
Add actual electronic contact information

### ISSUE THREAD

**Issue by emiliom** [uw-echospace/uw-echospace.github.io#2]
The Contact section only has the physical address to Henderson Hall. Not terribly useful, specially in Covid times!

Add email address(es). Could we create an alias somewhere that routes emails to all 3 of us?

Also add link to https://github.com/uw-echospace/

**Comment by leewujung** [comment]
Good idea! How about echospace@uw.edu? I can set this up.

**Comment by emiliom** [comment]
That's perfect. I just didn't know if that was something we could set up.

**Comment by leewujung** [comment]
Just got the email established. I'll get the edits in sometime later today.

Also, I just noticed that these issues are in this "shell" repo but not the [repo](https://github.com/uw-echospace/group-website) that contains the actual code/content. How about we move the issues there?

**Comment by emiliom** [comment]
Sounds good. I didn't realize this was not the repo where edits are made, until I was on the 2nd or 3rd issue

**Comment by leewujung** [comment]
Addressed here: https://github.com/uw-echospace/group-website/pull/24  🙂
