### ISSUE TITLE
Add link to awesome OER Aug '21 glider expedition article!

### ISSUE THREAD

**Issue by emiliom** [uw-echospace/uw-echospace.github.io#3]
@leewujung you probably pointed us to this expedition report before, but I don't remember seeing how fantastic it is!
https://oceanexplorer.noaa.gov/technology/development-partnerships/21adcp-gliders/welcome.html

You should definitely link to it from the Project section.

Frankly, it'd be even better if there was a prominent section on the web site for news items like this one.

**Comment by leewujung** [comment]
Haha, yes! I think I actually forgot to share this, because I was so buried... 

Agree that we should have a news section! We have quite a few recent and upcoming items (like the DAMC presentation) that can be linked! :D 

I'll take a stab at this.

**Comment by emiliom** [comment]
Right, the DMAC presentation would go there too. Plus your recent eScience presentation.
